# Alembic 配置文件

[alembic]
# A generic, single database configuration.

[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated scripts, such as code formatters, linters, etc.
#
# The format is:
#
# hook_name = script_or_function
#
# The function should accept the upgrade path as its first argument.
#
# There can be any number of additional arguments separated by spaces.

# log_template.py
# script_location = myapp.alembic.hooks:do_stuff

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S

