"""初始数据库架构

Revision ID: 0001
Revises: 
Create Date: 2025-01-01

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_specific_tips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_name', sa.String(length=100), nullable=False),
    sa.Column('tip_text', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False, default=0),
    sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, default=sa.func.now()),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_specific_tips_city_name'), 'city_specific_tips', ['city_name'], unique=False)

    op.create_table('weather_tip_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('weather_keyword', sa.String(length=50), nullable=False),
    sa.Column('tip_text', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False, default=0),
    sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, default=sa.func.now()),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_tip_templates_weather_keyword'), 'weather_tip_templates', ['weather_keyword'], unique=False)

    op.create_table('attraction_type_tips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attraction_type', sa.String(length=50), nullable=False),
    sa.Column('tip_text', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False, default=0),
    sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, default=sa.func.now()),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attraction_type_tips_attraction_type'), 'attraction_type_tips', ['attraction_type'], unique=False)

    op.create_table('attraction_keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attraction_type', sa.String(length=50), nullable=False),
    sa.Column('keyword', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, default=sa.func.now()),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attraction_keywords_attraction_type'), 'attraction_keywords', ['attraction_type'], unique=False)

    op.create_table('ticket_price_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('price_variance', sa.Float(), nullable=False, default=0.0),
    sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, default=sa.func.now()),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_price_rules_category_name'), 'ticket_price_rules', ['category_name'], unique=False)

    op.create_table('demo_spot_names',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_name', sa.String(length=100), nullable=False),
    sa.Column('spot_name', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False, default=0),
    sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, default=sa.func.now()),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demo_spot_names_city_name'), 'demo_spot_names', ['city_name'], unique=False)

    op.create_table('city_filter_keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_name', sa.String(length=100), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, default=sa.func.now()),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_filter_keywords_city_name'), 'city_filter_keywords', ['city_name'], unique=False)

    op.create_table('generic_tips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tip_text', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False, default=0),
    sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, default=sa.func.now()),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('technical_tip_keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, default=sa.func.now()),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('trip_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('itinerary_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, default=sa.func.now()),
    sa.Column('updated_at', sa.DateTime(), nullable=False, default=sa.func.now(), onupdate=sa.func.now()),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_records_trip_id'), 'trip_records', ['trip_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_records_trip_id'), table_name='trip_records')
    op.drop_table('trip_records')

    op.drop_table('technical_tip_keywords')
    op.drop_table('generic_tips')

    op.drop_index(op.f('ix_city_filter_keywords_city_name'), table_name='city_filter_keywords')
    op.drop_table('city_filter_keywords')

    op.drop_index(op.f('ix_demo_spot_names_city_name'), table_name='demo_spot_names')
    op.drop_table('demo_spot_names')

    op.drop_index(op.f('ix_ticket_price_rules_category_name'), table_name='ticket_price_rules')
    op.drop_table('ticket_price_rules')

    op.drop_index(op.f('ix_attraction_keywords_attraction_type'), table_name='attraction_keywords')
    op.drop_table('attraction_keywords')

    op.drop_index(op.f('ix_attraction_type_tips_attraction_type'), table_name='attraction_type_tips')
    op.drop_table('attraction_type_tips')

    op.drop_index(op.f('ix_weather_tip_templates_weather_keyword'), table_name='weather_tip_templates')
    op.drop_table('weather_tip_templates')

    op.drop_index(op.f('ix_city_specific_tips_city_name'), table_name='city_specific_tips')
    op.drop_table('city_specific_tips')
    # ### end Alembic commands ###

